"""Profile the starter workforce file and write docs/data_profile.md.

Run: uv run python scripts/profile_starter_data.py

Exploratory evidence only. Rules found here become quality checks in src/asteria/curate/.
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
EVENTS = ROOT / "data" / "raw-or-fixtures" / "starter" / "employee_lifecycle_events.csv"
OUT = ROOT / "docs" / "data_profile.md"
AS_OF = pd.Timestamp("2025-12-31")


def value_counts(df: pd.DataFrame, column: str) -> str:
    counts = df[column].fillna("<blank>").value_counts().sort_index()
    rows = "\n".join(f"| `{value}` | {count} |" for value, count in counts.items())
    return f"| {column} | rows |\n|---|---|\n{rows}"


def main() -> None:
    raw = pd.read_csv(EVENTS, dtype=str, keep_default_na=False).replace("", pd.NA)
    df = raw.drop_duplicates().copy()
    hire = pd.to_datetime(df["hire_date"])
    term = pd.to_datetime(df["termination_date"])
    tenure = (term - hire).dt.days

    checks: list[tuple[str, int, str]] = [
        ("Data rows", len(raw), "Includes duplicates"),
        ("Exact duplicate rows", int(raw.duplicated().sum()), "Identical on every column"),
        ("Distinct employee_id", raw["employee_id"].nunique(), ""),
        (
            "employee_id with conflicting rows",
            int((df.groupby("employee_id").size() > 1).sum()),
            "Same id, different values after exact dedup",
        ),
        ("Blank country_code", int(df["country_code"].isna().sum()), "Cannot join country signals"),
        (
            "Non-ISO country_code",
            int(df["country_code"].isin(["EL", "ROM"]).sum()),
            "`EL` = Eurostat Greece, `ROM` = Romania alias",
        ),
        ("Blank hire_date", int(hire.isna().sum()), "Cannot place in any cohort"),
        ("Hire before 2021-01-01", int((hire < "2021-01-01").sum()), "Outside objective window"),
        ("Hire after as-of", int((hire > AS_OF).sum()), ""),
        ("Termination before hire", int((tenure < 0).sum()), "Impossible tenure"),
        ("Termination after as-of", int((term > AS_OF).sum()), "Future information"),
        (
            "Termination date but blank type",
            int((term.notna() & df["termination_type"].isna()).sum()),
            "Exit reason unknown",
        ),
        (
            "Termination type but blank date",
            int((term.isna() & df["termination_type"].notna()).sum()),
            "",
        ),
        (
            "Voluntary exit, regretted blank",
            int(((df["termination_type"] == "Voluntary") & df["regretted_exit"].isna()).sum()),
            "Unknown, not false",
        ),
        (
            "Non-voluntary exit, regretted = true",
            int(
                (
                    df["termination_type"].isin(["Involuntary", "End of Contract"])
                    & (df["regretted_exit"] == "true")
                ).sum()
            ),
            "",
        ),
        (
            "End of Contract on Permanent employee",
            int(
                (
                    (df["termination_type"] == "End of Contract")
                    & (df["employment_type"] == "Permanent")
                ).sum()
            ),
            "Logical inconsistency",
        ),
        (
            "career_level = `Sr Mgmt`",
            int((df["career_level"] == "Sr Mgmt").sum()),
            "Unlisted label",
        ),
    ]

    exits = tenure[(tenure >= 175) & (tenure <= 190)].value_counts().sort_index()
    boundary = "\n".join(f"| {int(days)} | {count} |" for days, count in exits.items())

    lines = [
        "# Starter data profile",
        "",
        "Generated by `scripts/profile_starter_data.py` from "
        f"`{EVENTS.relative_to(ROOT).as_posix()}`. As-of date {AS_OF.date()}. "
        "Checks after exact-duplicate removal unless noted.",
        "",
        "## Checks",
        "",
        "| Check | Rows | Note |",
        "|---|---|---|",
        *(f"| {name} | {count} | {note} |" for name, count, note in checks),
        "",
        "## Ranges",
        "",
        f"- hire_date: {hire.min().date()} to {hire.max().date()}",
        f"- termination_date: {term.min().date()} to {term.max().date()}",
        f"- record_updated_at: {df['record_updated_at'].min()} to {df['record_updated_at'].max()}",
        "",
        "## Six-month boundary: exits by tenure day (175 to 190)",
        "",
        "| Tenure days | Exits |",
        "|---|---|",
        boundary,
        "",
        "## Categorical values",
        "",
        *(
            section
            for column in [
                "country_code",
                "business_unit",
                "career_level",
                "employment_type",
                "termination_type",
                "regretted_exit",
                "source_system",
            ]
            for section in (value_counts(df, column), "")
        ),
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    for name, count, _ in checks:
        print(f"{count:>6}  {name}")


if __name__ == "__main__":
    main()
